services:
  - type: web
    name: panthera-stories
    env: python
    buildCommand: apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
